import { useEffect } from 'react';
import FullCalendar from '@fullcalendar/react';
import timeGridPlugin from '@fullcalendar/timegrid';

// This component is specifically for print/PDF generation
function SchedulePrintView({ sections, studentInfo }) {
  
  // Convert sections to events
  const events = [];
  
  sections.forEach((section) => {
    const dept = section.course?.subjectAbbr || 'default';
    
    section.meetings?.forEach((meeting, meetingIndex) => {
      if (!meeting.days || meeting.days.length === 0 || !meeting.start) return;
      
      const [hours, minutes] = meeting.start.split(':').map(Number);
      const startTime = `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:00`;
      
      const endHours = Math.floor((hours * 60 + minutes + meeting.durationMin) / 60);
      const endMinutes = (hours * 60 + minutes + meeting.durationMin) % 60;
      const endTime = `${endHours.toString().padStart(2, '0')}:${endMinutes.toString().padStart(2, '0')}:00`;
      
      const dayMap = {
        'Sunday': 0, 'Monday': 1, 'Tuesday': 2, 'Wednesday': 3,
        'Thursday': 4, 'Friday': 5, 'Saturday': 6
      };
      
      meeting.days.forEach(day => {
        const dayOfWeek = dayMap[day];
        if (dayOfWeek === undefined) return;
        
        events.push({
          id: `${section.id}-${meetingIndex}-${day}`,
          title: `${section.course?.subjectAbbr} ${section.course?.number}`,
          daysOfWeek: [dayOfWeek],
          startTime: startTime,
          endTime: endTime,
          extendedProps: {
            instructor: meeting.instructors?.[0] || 'TBA',
            location: `${meeting.buildingCode} ${meeting.roomNumber}`,
            type: section.type
          }
        });
      });
    });
  });

  // Trigger print after render
  useEffect(() => {
    setTimeout(() => {
      window.print();
      // Close window after print (for PDF generation)
      setTimeout(() => {
        window.close();
      }, 100);
    }, 1000);
  }, []);

  return (
    <div className="print-view">
      {/* Header */}
      <div className="header">
        <div className="header-left">
          <h1>BoilerSchedule</h1>
          <p>Purdue University Course Schedule - Fall 2025</p>
        </div>
        {studentInfo && (
          <div className="header-right">
            <p><strong>{studentInfo.name}</strong></p>
            {studentInfo.major && <p>{studentInfo.major}</p>}
            {studentInfo.year && <p>{studentInfo.year}</p>}
            {studentInfo.email && <p>{studentInfo.email}</p>}
          </div>
        )}
      </div>

      {/* Schedule */}
      <div className="schedule-container">
        <FullCalendar
          plugins={[timeGridPlugin]}
          initialView="timeGridWeek"
          headerToolbar={false}
          weekends={false}
          allDaySlot={false}
          slotMinTime="07:00:00"
          slotMaxTime="22:00:00"
          slotDuration="00:30:00"
          slotLabelInterval="01:00:00"
          height="auto"
          expandRows={true}
          events={events}
          dayHeaderFormat={{ weekday: 'long' }}
          slotLabelFormat={{
            hour: 'numeric',
            minute: '2-digit',
            meridiem: 'short'
          }}
          eventOverlap={false}
          eventDisplay="block"
          displayEventTime={false}
          eventContent={(eventInfo) => {
            const props = eventInfo.event.extendedProps;
            return (
              <div className="event-content">
                <div className="event-type">{props.type?.slice(0, 3).toUpperCase()}</div>
                <div className="event-title">{eventInfo.event.title}</div>
                <div className="event-instructor">{props.instructor}</div>
                <div className="event-location">{props.location}</div>
              </div>
            );
          }}
        />
      </div>

      {/* Footer */}
      <div className="footer">
        <p>Generated by BoilerSchedule - Made by Umberto Puddu (upuddu@purdue.edu)</p>
        <p>Not affiliated with Purdue University</p>
      </div>

      <style jsx>{`
        @page {
          size: landscape;
          margin: 0.5in;
        }

        body {
          margin: 0;
          padding: 0;
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
        }

        .print-view {
          width: 100%;
          padding: 20px;
        }

        .header {
          display: flex;
          justify-content: space-between;
          margin-bottom: 20px;
          padding-bottom: 10px;
          border-bottom: 3px solid #CFB991;
        }

        .header-left h1 {
          margin: 0;
          color: #000;
          font-size: 24px;
        }

        .header-left p {
          margin: 5px 0 0 0;
          color: #666;
          font-size: 14px;
        }

        .header-right {
          text-align: right;
          font-size: 12px;
        }

        .header-right p {
          margin: 2px 0;
        }

        .schedule-container {
          margin: 20px 0;
        }

        .event-content {
          padding: 2px;
          font-size: 10px;
          position: relative;
        }

        .event-type {
          position: absolute;
          top: 2px;
          right: 2px;
          background: white;
          padding: 1px 3px;
          border-radius: 2px;
          font-size: 8px;
          font-weight: bold;
        }

        .event-title {
          font-weight: bold;
          font-size: 11px;
        }

        .event-instructor {
          font-size: 9px;
          opacity: 0.9;
        }

        .event-location {
          font-size: 9px;
          opacity: 0.8;
        }

        .footer {
          margin-top: 20px;
          padding-top: 10px;
          border-top: 1px solid #ddd;
          text-align: center;
          font-size: 10px;
          color: #666;
        }

        .footer p {
          margin: 2px 0;
        }

        /* FullCalendar print optimizations */
        .fc {
          font-size: 10pt !important;
        }

        .fc-event {
          border: 1px solid #333 !important;
          background: #f0f0f0 !important;
          color: #000 !important;
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }

        .fc-col-header-cell {
          background: #f5f5f5 !important;
          font-weight: bold !important;
        }

        .fc-timegrid-slot {
          height: 25px !important;
        }

        .fc-timegrid-slot-label {
          font-size: 10px !important;
        }

        /* Hide interactive elements */
        .fc-event-resizer,
        .fc-scrollgrid-shrink {
          display: none !important;
        }
      `}</style>
    </div>
  );
}

export default SchedulePrintView;
